nelmio_api_doc:
    documentation:
        info:
            title: MFI MountainPeaks
            description: Technical test - REST API for CRUDding mountain peaks
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
