version: "3"

services:

    web:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php

    php:
        build: docker/php
        volumes:
            - .:/app
        depends_on: 
            - database

    database:
        image: postgres:12
        environment: 
            POSTGRES_DB: mfi
            POSTGRES_USER: mfi
            POSTGRES_PASSWORD: mfi