version: "3"

services:

    database:
        image: postgres
        environment: 
            POSTGRES_DB: mfi
            POSTGRES_USER: mfi
            POSTGRES_PASSWORD: mfi
        ports:
            - 5432:5432